[package]
name = "templar-tools-common"
version = "0.2.4"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
cargo_metadata = "0.23.1"
templar-contract-artifacts = { workspace = true, features = ["workspace-loader"] }
templar-gateway-types.workspace = true

[lints]
workspace = true
