[package]
edition.workspace = true
rust-version.workspace = true
license.workspace = true
name = "templar-proxy-oracle-near-governance-contract"
repository.workspace = true
version = "0.3.5"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.near.reproducible_build]
image = "sourcescan/cargo-near:0.17.0-rust-1.86.0"
image_digest = "sha256:1784ca6310f3496f0048356ce420921c8f5fdf71ee8124d43a2e1ceb1f70db8a"
container_build_command = [
    "cargo",
    "near",
    "build",
    "non-reproducible-wasm",
    "--locked",
]

[dependencies]
getrandom.workspace = true
near-sdk.workspace = true
near-sdk-contract-tools.workspace = true
templar-common.workspace = true
templar-proxy-oracle-governance-kernel.workspace = true
templar-proxy-oracle-kernel.workspace = true
templar-proxy-oracle-near-common.workspace = true
templar-proxy-oracle-near-governance-common.workspace = true

[dev-dependencies]
anyhow.workspace = true
base64.workspace = true
near-api.workspace = true
near-sdk = { workspace = true, features = ["unit-testing"] }
rstest.workspace = true
serde_json.workspace = true
templar-common.workspace = true
templar-gateway-methods-spec.workspace = true
templar-gateway-testing.workspace = true
templar-proxy-oracle-near-governance-common.workspace = true
tokio.workspace = true

[lints]
workspace = true
