[package]
name = "templar-gateway-artifacts-spec"
version = "0.2.6"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
near-account-id.workspace = true
schemars.workspace = true
serde.workspace = true
templar-common = { workspace = true, features = ["non-contract-usage"] }
templar-contract-artifacts.workspace = true
templar-gateway-macros.workspace = true
templar-gateway-types.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
