[package]
name = "harvest-static-yield"
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
version = "0.1.8"

[dependencies]
anyhow.workspace = true
clap.workspace = true
near-account-id.workspace = true
near-api.workspace = true
templar-common = { workspace = true, features = ["rpc"] }
templar-gateway-client = { workspace = true, features = ["clap"] }
templar-gateway-methods-spec.workspace = true
templar-gateway-types.workspace = true
tokio.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing = { workspace = true, features = ["attributes"] }

[lints]
workspace = true
