[package]
name = "templar-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bigdecimal.workspace = true
near-contract-standards.workspace = true
near-sdk.workspace = true
thiserror.workspace = true

[lints]
workspace = true
