[package]
name = "templar-accumulator"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version = "0.1.8"

[[bin]]
name = "accumulator"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
near-account-id = { workspace = true }
near-api = { workspace = true }
templar-common = { workspace = true, features = ["rpc"] }
templar-gateway-client = { workspace = true, features = ["clap"] }
templar-gateway-methods-spec = { workspace = true }
templar-gateway-types = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
near-crypto = { workspace = true }
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
