[package]
name = "templar-relayer"
version = "0.4.1"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
axum = "0.8.4"
clap.workspace = true
dotenvy = "0.15.7"
futures.workspace = true
hex.workspace = true
near-api.workspace = true
near-contract-standards.workspace = true
near-crypto.workspace = true
near-jsonrpc-client.workspace = true
near-jsonrpc-primitives.workspace = true
near-primitives.workspace = true
near-sdk = { workspace = true, features = [
    "non-contract-usage",
    "unit-testing",
] }
near-sdk-contract-tools.workspace = true
sha2.workspace = true
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-native-tls",
    "postgres",
    "derive",
    "macros",
    "migrate",
    "rust_decimal",
    "uuid",
] }
templar-common = { workspace = true, features = ["rpc"] }
templar-gateway-client = { workspace = true, features = ["clap"] }
templar-gateway-core.workspace = true
templar-gateway-methods-dispatch.workspace = true
templar-gateway-methods-spec.workspace = true
templar-gateway-oracle-updates-dispatch = { workspace = true, features = ["clap"] }
templar-gateway-oracle-updates-spec.workspace = true
templar-gateway-store.workspace = true
templar-gateway-types.workspace = true
templar-proxy-oracle-kernel = { workspace = true, features = ["serde"] }
templar-proxy-oracle-near-common = { workspace = true }
templar-universal-account.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
uuid.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
tracing = { workspace = true, features = ["attributes"] }

[dev-dependencies]
anyhow.workspace = true
near-api.workspace = true
near-token.workspace = true
p256.workspace = true
reqwest = { version = "0.12.24", features = ["json"] }
rstest.workspace = true
serde_json.workspace = true
solana-sdk.workspace = true
templar-gateway-testing.workspace = true
test-utils.workspace = true

[lints]
workspace = true
