[package]
name = "templar-redstone-bridge"
version = "0.1.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
templar-common = { workspace = true, features = ["non-contract-usage"] }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
