[package]
name = "templar-market-monitor"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
version = "0.1.4"

[[bin]]
name = "market-monitor"
path = "src/main.rs"

[dependencies]
async-trait = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
clap = { workspace = true }
dotenv = "0.15"
futures = { workspace = true }
near-account-id = { workspace = true }
near-jsonrpc-client = { workspace = true }
near-jsonrpc-primitives = { workspace = true }
near-primitives = { workspace = true }
near-sdk = { workspace = true, features = ["non-contract-usage"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
templar-common = { workspace = true, features = ["rpc"] }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
