[package]
name = "templar-gateway-runtime"
version = "0.2.4"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
actix.workspace = true
async-trait.workspace = true
futures.workspace = true
near-api.workspace = true
templar-gateway-core.workspace = true
templar-gateway-types.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
